/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import crudgp.CrudGP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NICOLAS RIVERA
 */
public class GUI extends javax.swing.JFrame {

    CrudGP cc = new CrudGP();
    Connection con = cc.conexion();

    public GUI() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        textlabel = new javax.swing.JLabel();
        txtSNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPApellido = new javax.swing.JTextField();
        txtSApellido = new javax.swing.JTextField();
        cbTDocumento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CRPnombre = new javax.swing.JLabel();
        CRdocumento = new javax.swing.JLabel();
        CRPapellido = new javax.swing.JLabel();
        CRcorreo = new javax.swing.JLabel();
        CRtelefono = new javax.swing.JLabel();
        CRTdocumento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(138, 154, 199));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(33, 62, 121));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Documento:");

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Primer Nombre:");

        txtPNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPNombre.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtPNombreComponentAdded(evt);
            }
        });
        txtPNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPNombreInputMethodTextChanged(evt);
            }
        });
        txtPNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPNombreKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");

        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");

        txtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICOLAS RIVERA\\Downloads\\limpieza-de-datos.png")); // NOI18N
        btnAgregar.setText("Limpiar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICOLAS RIVERA\\Downloads\\disquete.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICOLAS RIVERA\\Downloads\\borrar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICOLAS RIVERA\\Downloads\\actualizar-base-de-datos.png")); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        textlabel.setForeground(new java.awt.Color(255, 255, 255));
        textlabel.setText("Segundo Nombre:");

        txtSNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNombreActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Primer Apellido:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Segundo Apellido:");

        txtPApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPApellidoActionPerformed(evt);
            }
        });
        txtPApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPApellidoKeyReleased(evt);
            }
        });

        txtSApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSApellidoActionPerformed(evt);
            }
        });

        cbTDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir tipo de documento", "Cedula de cuidadania", "Cedula de extranjeria", "Tarjeta de identidad", "Pasaporte", "NIT" }));
        cbTDocumento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbTDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTDocumentoItemStateChanged(evt);
            }
        });
        cbTDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbTDocumentoKeyReleased(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Documento:");

        CRPnombre.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRPnombre.setForeground(new java.awt.Color(204, 204, 204));

        CRdocumento.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRdocumento.setForeground(new java.awt.Color(204, 204, 204));
        CRdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CRdocumentoKeyReleased(evt);
            }
        });

        CRPapellido.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRPapellido.setForeground(new java.awt.Color(204, 204, 204));

        CRcorreo.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRcorreo.setForeground(new java.awt.Color(204, 204, 204));

        CRtelefono.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRtelefono.setForeground(new java.awt.Color(204, 204, 204));

        CRTdocumento.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CRTdocumento.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CRdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CRcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CRPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CRPnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(textlabel)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CRTdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSNombre)
                                        .addComponent(txtSApellido)
                                        .addComponent(txtTelefono)
                                        .addComponent(cbTDocumento, 0, 143, Short.MAX_VALUE)))))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CRtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textlabel)
                    .addComponent(txtSNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CRPnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CRPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CRTdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CRtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CRcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnAgregar))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        tablaGP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaGP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaGP);

        jLabel5.setText("Busqueda:");

        txtBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICOLAS RIVERA\\OneDrive - GENCELL PHARMA\\Documentos\\Imagen1.png")); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(221, 221, 221))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        insertarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed
    public void FiltrarDatos(String valor) {

        String[] titulos = {"ID", "Documento", "Primer Nombre","Segundo Nombre","Primer Apellido","Segundo Apellido", "Telefono", "Correo", "Tipo de Documento"};
        String[] registros = new String[10];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from crud1 where documento like '%"+valor+"%'";

        try {

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("ID");
                registros[1] = rs.getString("Documento");
                registros[2] = rs.getString("PrimerNombre");
                registros[3] = rs.getString("SegundoNombre");
                registros[4] = rs.getString("PrimerApellido");
                registros[5] = rs.getString("SegundoApellido");
                registros[6] = rs.getString("Telefono");
                registros[7] = rs.getString("Correo");
                registros[8] = rs.getString("TipodeDocumento");

                modelo.addRow(registros);

            }

            tablaGP.setModel(modelo);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Error al mostrar datos" + e.getMessage());
        }
    }

    public void mostrarDatos() {

        String[] titulos = {"ID", "Documento", "Primer Nombre","Segundo Nombre","Primer Apellido","Segundo Apellido", "Telefono", "Correo", "Tipo de Documento"};
        String[] registros = new String[10];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from crud1";

        try {

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("ID");
                registros[1] = rs.getString("Documento");
                registros[2] = rs.getString("PrimerNombre");
                registros[3] = rs.getString("SegundoNombre");
                registros[4] = rs.getString("PrimerApellido");
                registros[5] = rs.getString("SegundoApellido");
                registros[6] = rs.getString("Telefono");
                registros[7] = rs.getString("Correo");
                registros[8] = rs.getString("TipodeDocumento");

                modelo.addRow(registros);

            }

            tablaGP.setModel(modelo);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Error al mostrar datos " + e.getMessage());
        }
    }
    public void validar (){
        if(txtPNombre.getText().isEmpty()){
            CRPnombre.setText("*Campo Requerido*");
        }else{
            CRPnombre.setText("");
        }
        if(txtPApellido.getText().isEmpty()){
            CRPapellido.setText("*Campo Requerido*");
        }else{
            CRPapellido.setText("");
        }
        if(txtID.getText().isEmpty()){
            CRdocumento.setText("*Campo Requerido*");
        }else{
            CRdocumento.setText("");
        }
        if(txtCorreo.getText().isEmpty()){
            CRcorreo.setText("*Campo Requerido*");
        }else if(!txtCorreo.getText().contains("@") || !txtCorreo.getText().contains(".")){
            CRcorreo.setText("*Correo invalido*");
        }else{
            CRcorreo.setText("");
        }
        if(txtTelefono.getText().isEmpty()){
            CRtelefono.setText("*Campo Requerido*");
        }else{
            CRtelefono.setText("");
        }
        if(cbTDocumento.getSelectedItem().equals("Elegir tipo de documento")){
            CRTdocumento.setText("*Campo Requerido*");
        }else{
            CRTdocumento.setText("");
        }
        if(txtPNombre.getText().isEmpty() || txtPApellido.getText().isEmpty() || txtID.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtTelefono.getText().isEmpty() || CRcorreo.getText().equals("*Correo Invalido") || cbTDocumento.getSelectedItem().equals("Elegir tipo de documento")){
            btnGuardar.setEnabled(false);
        }else{
         btnGuardar.setEnabled(true);
        }
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaGPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGPMouseClicked

        int filaSeleccionada = tablaGP.rowAtPoint(evt.getPoint());

        txtID.setText(tablaGP.getValueAt(filaSeleccionada, 1).toString());
        txtPNombre.setText(tablaGP.getValueAt(filaSeleccionada, 2).toString());
        txtSNombre.setText(tablaGP.getValueAt(filaSeleccionada, 3).toString());
        txtPApellido.setText(tablaGP.getValueAt(filaSeleccionada, 4).toString());
        txtSApellido.setText(tablaGP.getValueAt(filaSeleccionada, 5).toString());
        txtTelefono.setText(tablaGP.getValueAt(filaSeleccionada, 6).toString());
        txtCorreo.setText(tablaGP.getValueAt(filaSeleccionada, 7).toString());
        cbTDocumento.setSelectedItem(tablaGP.getValueAt(filaSeleccionada, 8));

    }//GEN-LAST:event_tablaGPMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ActualizarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminatRegistros();
        mostrarDatos();
        limpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        FiltrarDatos(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtSNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNombreActionPerformed

    private void txtPApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPApellidoActionPerformed

    private void txtSApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSApellidoActionPerformed

    private void txtPNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPNombreKeyReleased
        validar();
    }//GEN-LAST:event_txtPNombreKeyReleased

    private void txtPApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPApellidoKeyReleased
        validar();
    }//GEN-LAST:event_txtPApellidoKeyReleased

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        validar();
    }//GEN-LAST:event_txtIDKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        validar();
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        validar();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void CRdocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CRdocumentoKeyReleased
        validar();
    }//GEN-LAST:event_CRdocumentoKeyReleased

    private void cbTDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTDocumentoKeyReleased
        
    }//GEN-LAST:event_cbTDocumentoKeyReleased

    private void cbTDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTDocumentoItemStateChanged
        validar();
    }//GEN-LAST:event_cbTDocumentoItemStateChanged

    private void txtPNombreComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtPNombreComponentAdded

    }//GEN-LAST:event_txtPNombreComponentAdded

    private void txtPNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPNombreInputMethodTextChanged
       
    }//GEN-LAST:event_txtPNombreInputMethodTextChanged
    public void limpiarCajas() {
        txtPNombre.setText("");
        txtSNombre.setText("");
        txtPApellido.setText("");
        txtSApellido.setText("");
        txtCorreo.setText("");
        txtID.setText("");
        txtTelefono.setText("");
        cbTDocumento.setSelectedItem("Elegir tipo de documento");
        
    }

    public void eliminatRegistros() {
        int filaSeleccionada = tablaGP.getSelectedRow();

        try {
            String SQL = "delete from crud1 where id=" + tablaGP.getValueAt(filaSeleccionada, 0);

            Statement st = con.createStatement();

            int n = st.executeUpdate(SQL);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar registro" + e.getMessage());
        }

    }

    public void ActualizarDatos() {
        try {

            String SQL = "update crud1 set documento=?,primernombre=?,segundonombre=?,primerapellido=?,segundoapellido=?,telefono=?,correo=?,tipodedocumento=? where ID=? ";

            int filaSeleccionado = tablaGP.getSelectedRow();
            String dao = (String) tablaGP.getValueAt(filaSeleccionado, 0);
            PreparedStatement pst = con.prepareStatement(SQL);

            pst.setString(1, txtID.getText());
            pst.setString(2, txtPNombre.getText());
            pst.setString(3, txtSNombre.getText());
            pst.setString(4, txtPApellido.getText());
            pst.setString(5, txtSApellido.getText());
            pst.setString(6, txtTelefono.getText());
            pst.setString(7, txtCorreo.getText());
            int seleccionado= cbTDocumento.getSelectedIndex();
            pst.setString(8, cbTDocumento.getItemAt(seleccionado));

            pst.setString(9, dao);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Registro Editado Exitoso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Edicion " + e.getMessage());
        }
    }

    public void insertarDatos() {
        try {

            String SQL = "insert into crud1 (Documento, PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Telefono, Correo, TipodeDocumento) values (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);

            pst.setString(1, txtID.getText());
            pst.setString(2, txtPNombre.getText());
            pst.setString(3, txtSNombre.getText());
            pst.setString(4, txtPApellido.getText());
            pst.setString(5, txtSApellido.getText());
            pst.setString(6, txtTelefono.getText());
            pst.setString(7, txtCorreo.getText());
            int seleccionado1= cbTDocumento.getSelectedIndex();
            pst.setString(8, cbTDocumento.getItemAt(seleccionado1));

            pst.execute();

            JOptionPane.showMessageDialog(null, "Registro Exitoso ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Registro " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CRPapellido;
    private javax.swing.JLabel CRPnombre;
    private javax.swing.JLabel CRTdocumento;
    private javax.swing.JLabel CRcorreo;
    private javax.swing.JLabel CRdocumento;
    private javax.swing.JLabel CRtelefono;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGP;
    private javax.swing.JLabel textlabel;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPApellido;
    private javax.swing.JTextField txtPNombre;
    private javax.swing.JTextField txtSApellido;
    private javax.swing.JTextField txtSNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
